# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python3 -m venv scripts/.venv
        source scripts/.venv/bin/activate
        pip install -r scripts/requirements.txt
    - name: Init vars
      run: |
        export PLANET=https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf
        export PLANET_METRO="$HOME/metro/planet-metro.osm.pbf"
        export TMPDIR="$HOME/metro/tmp"
        export HTML_DIR="$HOME/metro/tmp_html"
        export DUMP="$HTML_DIR"
    - name: Run script
      run: scripts/process_subways.sh
